// Action Types
export const STATUS = {
  STARTED: "STARTED",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE"
};

const WAREHOUSE = {
  GET_ALL_WAREHOUSES: "GET_ALL_WAREHOUSES",
  GET_WAREHOUSE: "GET_WAREHOUSE",
  NEW_WAREHOUSE: "NEW_WAREHOUSE",
  UPDATE_WAREHOUSE: "UPDATE_WAREHOUSE",
  DELETE_WAREHOUSE: "DELETE_WAREHOUSE"
};
